name: Deploy Loja de Carros

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy PHP Application Files
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST_LCW }}
          user: ${{ secrets.DEPLOY_USER_LCW }}
          password: ${{ secrets.DEPLOY_PASSWORD_LCW }}
          remoteDir: 'sistema'
          localDir: './'

      - name: Setup Composer
        uses: php-actions/composer@v6
        with:
          php_version: '8.3.7'
          args: --optimize-autoloader --no-dev
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_key_pub: ${{ secrets.SSH_KEY_PUB }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy Front with FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST_LCW }}
          user: ${{ secrets.DEPLOY_USER_LCW }}
          password: ${{ secrets.DEPLOY_PASSWORD_LCW }}
          remoteDir: 'public_html/admin/'
          localDir: './public/'
          options: '--delete'
